version: '3'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    container_name: plants-api
    restart: always
    volumes:
      - plants-api-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: plants-api

volumes:
  plants-api-disk: